services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    user: "redis:redis"

  postgres:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"

  outline:
    build:        # This uses your Dockerfile in the current dir
      context: .
      dockerfile: Dockerfile
    image: outline-personalmods
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
      - docker.env
    volumes:
      - ./storage-data:/var/lib/outline/data
    restart: unless-stopped
